plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
}

base {
	archivesName = project.archives_base_name
}

repositories {
	maven {
		name = 'Nucleoid'
		url = 'https://maven.nucleoid.xyz/'
	}
}

fabricApi {
	configureTests {
		createSourceSet = true
		modId = "particledeco-gametest"
		enableGameTests = true
		enableClientGameTests = false
		eula = true
	}
}

loom {
	mods {
		"particledeco" {
			sourceSet sourceSets.main
		}
	}
	runs {
		gameTest {
			property "fabric-api.gametest.report-file", project.layout.buildDirectory.file("gametest-junit.xml").get().asFile.absolutePath
		}
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

	// Server side GUI library, bundled as jar-in-jar.
	implementation "eu.pb4:sgui:${project.sgui_version}"
	include "eu.pb4:sgui:${project.sgui_version}"
}

processResources {
	def version = project.version
	inputs.property "version", version

	filesMatching("fabric.mod.json") {
		expand "version": version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
	it.options.encoding = "UTF-8"
}

java {
	withSourcesJar()
	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

jar {
	def projectName = project.name
	inputs.property "projectName", projectName

	from("LICENSE") {
		rename { "${it}_$projectName" }
	}
}
